import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import NextAuthProvider from "./components/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

 
  
  return (
    <html lang="en">
      <body className={`${inter.className}  dark:bg-bgDark dark:text-white `}>
        <NextAuthProvider>
          <Nav />
          <div className=" max-w-6xl mx-auto shadow-2xl  px-4">{children}</div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
